# Generated by Django 5.2.6 on 2025-09-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('contractor', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('completion_date', models.DateField()),
            ],
        ),
    ]
